codecov:
  token: 97bfb416-2521-4e76-b000-d8b014fb6a5c
  require_ci_to_pass: yes


paths:
  - "model/"
  - "model/ErrorHandlers/"
  - "model/saveload.py"

coverage:
  round: down

  status:
    project:
      default:
        path: model/
        target: 80%

